name: Deploy to GitHub Pages

on:
    push:
      tags:
        - "v*"
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Checkout your repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Node.js 
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Install dependencies and build
      - name: Install dependencies and build
        run: |
          if [ -f package.json ]; then
            npm install
          fi

      - name: Prepare dist directory
        run: |
          mkdir -p dist
          cp -r images dist/
          cp *.html dist/
          cp *.css dist/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist


